PoC/urls.py
from django.urls import path

from . import views

app_name = 'PoC'
urlpatterns = [
    path('', views.index, name='index'),
    path('', views.index, name='index'),
    path('sysserialno/<str:sysserialno>/', views.serial_detail, name='serial_detail'),
    path('line_detail/<str:line>/<str:stage>/<int:inSLA>', views.line_detail, name='line_detail'),

]

testAppDjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('PoC/', include('PoC.urls')),
    path('admin/', admin.site.urls),
    #path('polls/', include('polls.urls')),
]

PoC/models.py
from django.db import models

class CT_Stages(models.Model):
    stageCode = models.IntegerField()
    stageName = models.CharField(max_length=15)
    slatime = models.IntegerField()

    def __str__(self):
        return self.stageName


class SfcPoc(models.Model):
    workorderno = models.CharField(max_length=50)
    productlevel = models.CharField(max_length=30, blank=True, null=True)
    productionline = models.CharField(max_length=20)
    routeid = models.CharField(max_length=10)
    sysserialno = models.CharField(primary_key=True, max_length=20)
    platform = models.CharField(db_column='platform', max_length=50, blank=True, null=True)  # Field name made lowercase.
    basemod = models.CharField(db_column='basemod', max_length=20, blank=True, null=True)  # Field name made lowercase.
    ordertype = models.CharField(db_column='ordertype', max_length=20, blank=True, null=True)  # Field name made lowercase.
    scheduledate = models.DateTimeField(blank=True, null=True)
    assyin_date = models.DateTimeField(db_column='assyin_date', blank=True, null=True)  # Field name made lowercase.
    assyout_date = models.DateTimeField(db_column='assyout_date', blank=True, null=True)  # Field name made lowercase.
    testin_date = models.DateTimeField(db_column='testin_date', blank=True, null=True)  # Field name made lowercase.
    testout_date = models.DateTimeField(db_column='testout_date', blank=True, null=True)  # Field name made lowercase.
    packin_date = models.DateTimeField(db_column='packin_date', blank=True, null=True)  # Field name made lowercase.
    packout_date = models.DateTimeField(db_column='packout_date', blank=True, null=True)  # Field name made lowercase.
    shipin_date = models.DateTimeField(db_column='shipin_date', blank=True, null=True)  # Field name made lowercase.
    shipout_date = models.DateTimeField(db_column='shipout_date', blank=True, null=True)  # Field name made lowercase.
    currentevent = models.CharField(max_length=30, blank=True, null=True)
    nextevent = models.CharField(max_length=30, blank=True, null=True)
    etltime = models.DateTimeField(db_column='etltime', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'sfc_poc'

class ct_view(models.Model):
    productionline = models.CharField(max_length=20)
    sysserialno = models.CharField(primary_key=True, max_length=20)
    workorderno = models.CharField(max_length=50)
    assy = models.BigIntegerField()
    test = models.BigIntegerField()
    pack = models.BigIntegerField()
    ship = models.BigIntegerField()
    stage = models.CharField(max_length=20)
    sla_time = models.IntegerField()
    insla = models.IntegerField()
    elapsed_time = models.BigIntegerField()
    currentevent = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'poc_ct_view'

PoC/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.db.models import Count
import pdb
from django.db import connection
from .models import CT_Stages, ct_view, SfcPoc

def index(request):
    # cursor = connection.cursor()
    # # Write the SQL code
    # sql_string = 'SELECT * FROM poc_ct_view'
    # # Execute the SQL
    # cursor.execute(sql_string)
    # result = cursor.fetchall()

    line_data_dict = {}

    stage_list = CT_Stages.objects.order_by('stageCode')
    # group by
    # line_data_count_raw = ct_view.objects\
    #     .values('productionline', 'stage', 'inSLA')\
    #     .annotate(cnt=Count('sysserialno'))\
    #     .order_by('productionline','stage','inSLA')

    line_data_raw_columns = ['productionline', 'sysserialno', 'workorderno', 'stage','insla','elapsed_time','currentevent']
    line_data_raw = ct_view.objects.values(*line_data_raw_columns).order_by('-elapsed_time')

    workorder_data = {}
    for line_data in line_data_raw:
        if line_data['workorderno'] not in workorder_data:
            workorder_data[line_data['workorderno']] = [0,0]
        if workorder_data[line_data['workorderno']][1] < int(line_data['elapsed_time']):
            workorder_data[line_data['workorderno']][1] = int(line_data['elapsed_time'])
        workorder_data[line_data['workorderno']][0] += 1

    line_data_grouped = line_data_raw\
        .values('productionline', 'stage', 'insla') \
        .annotate(cnt=Count('sysserialno')) \
        .order_by('productionline', 'stage', 'insla')

    print(workorder_data)

    for line_data in line_data_grouped:
        if not line_data['productionline'] in line_data_dict:
            line_data_dict[line_data['productionline']] = { i.stageName:{'insla':0,'outsla':0} for i in stage_list}
        try:
            line_data_dict[line_data['productionline']][line_data['stage']]['insla' if int(line_data['insla'])==1 else 'outsla'] = \
                line_data['cnt']
        except KeyError as e:
            pass
    print(line_data_grouped.query)
    context = {
        'stage_list': stage_list,
        'line_data_dict': line_data_dict,
        'line_data_raw': line_data_raw,
        'line_data_raw_columns': line_data_raw_columns,
        'workorder_data': workorder_data,
    }

    return render(request, 'PoC/index.html', context)



def serial_detail(request, sysserialno):
    serial_qs = SfcPoc.objects.filter(sysserialno=sysserialno)

    serial_qs_fileds = [f.name for f in SfcPoc._meta.get_fields()]
    testing = {}

    for k, v in serial_qs.values()[0].items():
        testing[k] = v
    context ={
        'serial_qs': testing,
        'serial_qs_fileds':serial_qs_fileds,
    }

    return render(request, 'PoC/serialno_detail.html', context)

def line_detail(request, line, stage, inSLA):
    line_data_raw_columns = ['productionline', 'sysserialno', 'workorderno', 'stage', 'insla', 'elapsed_time',
                             'currentevent']
    line_data_raw = ct_view.objects.values(*line_data_raw_columns).filter(productionline=line,
                                                                          insla=int(inSLA),stage=stage).order_by('-elapsed_time')

    context = {
        'line_data_raw': line_data_raw,
        'line_data_raw_columns': line_data_raw_columns,
    }
    print(request,line,stage,inSLA)
    print(line_data_raw.query)
    return render(request, 'PoC/line_detail.html', context)

PoC/templates/PoC/index.html
{% load static %}
{% load filters %}
<head>
    <meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1.0" /><title>Cycle Time</title>


    <link rel="stylesheet" href="{% static 'PoC/styles/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'PoC/styles/fonts/material-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'PoC/styles/navbar.css' %}" />


    <script src="{% static 'PoC/scripts/jquery.min.js' %}"></script>
    <script src="{% static 'PoC/scripts/bootstrap.min.js' %}"></script>

    <link href="{% static 'PoC/styles/styles.css' %}" rel="stylesheet" />
    <link href="{% static 'PoC/styles/CycleTimeR.css' %}" rel="stylesheet" />

    <script type="text/javascript" src="{% static 'PoC/scripts/cycle_time.js' %}"></script>


    <link rel="stylesheet" type="text/css" href="{% static 'PoC/styles/style.css' %}">
    {# <link rel="stylesheet" type="text/css" href="{% static 'PoC/styles/CycleTimeR.css' %}"> #}

</head>

<body class="bodyback">


    <header>
        <section class="headerlog">
            <div class="logotitle"><a class="hidden-xs logo" href="Default.aspx">Foxconn </a><a href="#" class="titlesite">Cycle Time</a></div>
         </section>

    </header>

    <div id="body">

        <section class="content-wrapper main-content clear-fix">
        <div class="se-pre-con"></div>

            <div class="containertable transback">
            <section>
                <div>
                    <div class="blg_sel"><button type="button" class="btn btn-primary">A1</button></div>
                    <div class="blg_sel"><button type="button" class="btn btn-primary">A2</button></div>
                    <div class="blg_sel"><button type="button" class="btn btn-primary">A3</button></div>
                    <div class="blg_sel"><h1 class="building_line"><span id="lbl_building">A1</span></h1></div>
                </div>


            <div id="LineView">

            <div class="tbl-header"><table cellpadding="0" cellspacing="0" border="0"><thead>
            <th>DFMSLINE</th>
            {% for stage in stage_list %}
                <th class="centerhead">
                    <div>{{ stage.stageName }}</div>
                    <div class ="subhead">
                        <div>PD</div>
                    </div>
                </th>
            {% endfor %}
            </thead></table></div>

            <div class="tbl-content"><table cellpadding="0" cellspacing="0" border="0">
            {% for l_key, l_data in line_data_dict.items %}
            <tbody><tr>
            	<td rowspan="4">
                    <div class="linecol">
                        <div class="line">{{ l_key }}</div>
                        <div class="onsla">
                            <div>in SLA</div>
                            <div>Not in SLA</div>
                        </div>
                    </div>
                </td>
                {% for stage in stage_list %}
                    <td><div class="subtitable ontime">
                        <div class="square">
                            <div class="green"><a href="{% url 'PoC:line_detail' l_key stage.stageName 1 %}" class="fill-div">
                                {{ l_data|gkey:stage.stageName|gkey:'insla' }}
                            </a></div>

                        </div></div>
                        <div class="subtitable outtime">
                            <div class="red"><a href="{% url 'PoC:line_detail' l_key stage.stageName 0 %}" class="fill-div">
                                {{ l_data|gkey:stage.stageName|gkey:'outsla' }}
                            </a></div>

                    </div></td>

                {% endfor %}
            </tr></tbody>
            {% endfor %}
            </table></div>

            </div>

            <div id="Line_Detail">
                {% include './line_detail.html' %}
            </div>


            <div id="WorkorderView">
                <div class="tbl-header"><table cellpadding="0" cellspacing="0" border="0"><thead>
                <th class="centerhead">
                    <div>Work Order</div>
                </th>
                <th class="centerhead">
                    <div>Qty</div>
                </th>
                <th class="centerhead">
                    <div>Aging</div>
                </th>
                </thead></table></div>
                <div class="tbl-content"><table cellpadding="0" cellspacing="0" border="0">
                {% for wo,data in workorder_data.items %}
                    <tbody><tr>
                    <td rowspan="4">
                        <div class="linecol">
                        <div class="">{{ wo }}</div>
                    </div></td>
                    <td rowspan="4">
                        <div class="linecol">
                        <div class="">{{ data.0 }}</div>
                    </div></td>
                    <td rowspan="4">
                        <div class="linecol">
                        <div class="">{{ data.1 }}</div>
                    </div></td>
                </tr></tbody>
                {% endfor %}
                </table></div>
            </div>

            <div id="SerialDetailResult"></div>

            </section>
            </div>
        </section>
    </div>
</body>

PoC/templates/PoC/line_detail.html
<div class="tbl-header"><table cellpadding="0" cellspacing="0" border="0"><thead>
{% for column_name in line_data_raw_columns %}
    <th class="centerhead">
        <div>{{ column_name }}</div>
    </th>
{% endfor %}
</thead></table></div>
<div class="tbl-content"><table cellpadding="0" cellspacing="0" border="0">
{% for data_row in line_data_raw %}
    <tbody><tr>
    {% for n, col in data_row.items %}
        <td rowspan="4">
        <div class="linecol">
        {% if n == 'sysserialno' %}
            <div class=""><a href="{% url 'PoC:serial_detail' col %}" class="fill-div">{{ col }}</a></div>
        {% else %}
            <div class="">{{ col }}</div>
        {% endif %}
    </div></td>
    {% endfor %}
</tr></tbody>
{% endfor %}
</table></div>

PoC/templates/PoC/serialno_detail.html
{% load filters %}

<div class="tbl-header"><table cellpadding="0" cellspacing="0" border="0"><thead>
    <tr>
    <th class="centerhead" colspan="2">
        <div>{{ serial_qs|gkey:'sysserialno' }}</div>
    </th></tr>
    <tr>
        <th class="centerhead">key</th>
        <th class="centerhead">value</th>
    </tr>
</thead></table></div>
<div class="tbl-content"><table cellpadding="0" cellspacing="0" border="0">
{% for k,v in serial_qs.items %}
    <tbody><tr>
    <td rowspan="4">
        <div class="linecol">
            <div class="">{{ k }}</div>
        </div>
    </td>
    <td rowspan="4">
        <div class="linecol">
            <div class="">{{ v }}</div>
        </div>
    </td>
    </tr></tbody>

{% endfor %}
</table></div></div>